var stations = ["HT", "HTO", "HDE", "ATN", "AC", "AKM", "AMR", "AMRN", "AML", "AMRI", "ALMB", "ALM", "ALMM", "ALMO", "ALMP", "AMPO", "APN", "AMF", "AMFS", "AVAT", "ASA", "ASB", "ASHD", "ASDL", "ASDM", "RAI", "ASSP", "ASS", "VMW", "ASDZ", "ANA", "APD", "APDM", "APDO", "APG", "AKL", "ARN", "AH", "AHPR", "AHP", "AHZ", "ASN", "BRN", "NSCH", "BF", "BRD", "BNC", "BNN", "BNZ", "BDM", "BK", "BSD", "BL", "BGN", "BET", "BV", "BHV", "BR", "BLL", "BDG", "BN", "BSK", "BSKS", "BHDV", "BKF", "BKG", "BMR", "BTL", "BD", "BDPB", "BKL", "BMN", "BP", "BDE", "BNK", "BSMZ", "CPS", "CAS", "CVM", "CO", "CK", "CL", "DA", "DLN", "DL", "DVNK", "DWE", "DEI", "DDN", "DT", "DTZ", "DZ", "DZW", "DLD", "GVC", "GV", "LAA", "GVM", "GVMW", "YPB", "HDR", "HDRZ", "DN", "DV", "DVC", "DID", "DMN", "DMNZ", "DR", "DTC", "DTCH", "DDR", "DDRS", "DDZD", "DB", "DRH", "DRP", "DRON", "DVN", "DVD", "EC", "EDC", "ED", "EEM", "EDN", "EHV", "EHS", "EST", "EMN", "EMNZ", "EKZ", "ES", "ESE", "ESK", "EML", "ETN", "EGH", "EGHM", "WTM", "FWD", "FN", "GDR", "GDM", "GP", "GLN", "LUT", "GZ", "GBR", "GS", "GO", "GR", "GD", "GDG", "GBG", "GK", "GN", "GERP", "GNN", "GW", "WIJ", "HLM", "HLMS", "HWZB", "HDB", "HD", "HBZM", "GND", "HRN", "HRNOVT", "HLG", "HLGH", "HK", "HAD", "HR", "HRY", "HWD", "HRL", "HRLK", "HRLW", "HZE", "HLO", "HNO", "HM", "HMH", "HMBV", "HMBH", "HMN", "HGL", "HGLG", "HGLO", "HIL", "HVS", "HVSM", "HVSP", "HNP", "HB", "HVL", "HOR", "HON", "HFD", "HGV", "HGZ", "HKS", "HN", "HNK", "HRT", "HTN", "HTNC", "SGL", "HDG", "IJT", "KPN", "KPNZ", "BZL", "KRD", "KTR", "KBK", "KMR", "KZ", "KMW", "KBD", "KMA", "KW", "KRG", "ZLW", "LG", "LLZM", "LDM", "LW", "LWC", "LEDN", "LDL", "LLS", "LTV", "LC", "LP", "LTN", "MZ", "MRN", "MAS", "MT", "MTN", "MTR", "MG", "MRB", "MTH", "MES", "MP", "MDB", "MMLH", "NDB", "NA", "NVP", "NWK", "NKK", "NM", "NMD", "NMGO", "NMH", "NML", "NVD", "NS", "NH", "OBD", "OT", "ODZ", "OST", "OMN", "OTB", "OP", "O", "OW", "ODB", "OVN", "PMR", "PMO", "PMW", "PT", "RAT", "RVS", "RV", "RH", "RHN", "RSN", "RSW", "RB", "RM", "RD", "RSD", "RS", "RTA", "RTB", "RTD", "RLB", "RTN", "RTST", "RTZ", "RL", "SPTN", "SPTZ", "SPM", "SSH", "SWD", "SGN", "SDA", "SDM", "SOG", "SN", "SHL", "SPV", "STD", "SDT", "SDTB", "SK", "SKND", "ST", "STZ", "SD", "SBK", "SPH", "STV", "STM", "SWK", "SRN", "SM", "TG", "TBG", "TL", "TPSW", "TB", "TBR", "TBU", "TWL", "UTG", "UHZ", "UHM", "UST", "UT", "UTLR", "UTLN", "UTM", "UTO", "UTT", "UTVR", "UTZL", "VK", "VSV", "VDM", "VNDC", "VNDW", "KLP", "VP", "VL", "VRY", "VLB", "VTN", "VS", "VSS", "VDL", "VB", "VH", "VST", "VEM", "VD", "VZ", "VHP", "VG", "WAD", "WADN", "WADT", "WFM", "WT", "WP", "WL", "WTV", "WZ", "WDN", "WC", "WH", "WS", "WSM", "WW", "WWW", "WD", "WF", "WV", "WK", "WM", "ZD", "ZDK", "ZZS", "ZBM", "ZVT", "ZA", "ZV", "ZVB", "ZTM", "ZTMO", "ZB", "ZH", "ZP", "ZWD", "ZL", "ZLSH"];


function loadPage(that, i) {
    setTimeout(function () {
        console.log(stations[i]);
        that.document.location = "https://www.ns.nl/reisplanner/#/?aankomst=ASD&aankomsttype=treinstation&vertrek=" + stations[i] + "&vertrektype=treinstation&type=aankomst&tijd=2018-11-12T09:00";
        if (i < 403) {
            oadPage(that, i + 1);
        }
    }, 3000)
}

loadPage(this, 0);